bikeData = [
  {
    id: 1,
    make: "Santa Cruz",
    model: "Hightower",
    suspensionTravel: 150,
    wheelSize: "29",
    ridingStyle: "Trail",
    terrain: "Rocky chunky and technical",
    skillLevel: "Beginner Intermediate",
    price: 5099,
    imageUrl:
      "https://www.santacruzbicycles.com/_next/image?url=https%3A%2F%2Fimages.prismic.io%2Fsantacruzbikesstatic%2F3007f469-644f-47dd-9adb-b568905673b8_MY24_HT_Red.jpg%3Fauto%3Dcompress%2Cformat&w=1400&q=99",
    description:
      "Big on wheels, medium on travel, short on fuss, this is the do-it-all bike that does it over and over again thanks to a versatile balance of geo, spec and durability.",
    favorite: false,
  },
  {
    id: 2,
    make: "Santa Cruz",
    model: "Tallboy",
    suspensionTravel: 120,
    wheelSize: "29",
    ridingStyle: "Trail",
    terrain: "Smooth and flowy with some technical rocks",
    skillLevel: "Beginner Intermediate",
    price: 4899,
    imageUrl:
      "https://www.santacruzbicycles.com/_next/image?url=https%3A%2F%2Fimages.prismic.io%2Fsantacruzbikesstatic%2F6dc56878-5e6d-4e5a-a67b-e33534018ab4_MY24_TB_Orange.jpg%3Fauto%3Dcompress%2Cformat&w=1400&q=99",
    description:
      "The Tallboy has earned a loyal following amongst those who seek a go-to bike that will hold up to the relentless hammering of power hour rides or riding for all-the-hours.",
    favorite: false,
  },
  {
    id: 3,
    make: "Santa Cruz",
    model: "Nomad",
    suspensionTravel: 170,
    wheelSize: "MX 29/27.5",
    ridingStyle: "Enduro",
    terrain: "Rocky chunky and technical",
    skillLevel: "Intermediate Advanced",
    price: 4999,
    description:
      "Load up the van, hit the road, climb a mountain, hammer it back down, huck the gap, throw the bike back in the van, drive to the bike park and do laps on laps. Hell, you could even rock up to the startline of the world's wildest races.",
    imageUrl:
      "https://www.santacruzbicycles.com/_next/image?url=https%3A%2F%2Fimages.prismic.io%2Fsantacruzbikesstatic%2Fd2cfaf5e-61fe-4fa3-b335-9bccacc38bbd_MY24_Nomad_Blue.jpg%3Fauto%3Dcompress%2Cformat&w=1400&q=99",
    favorite: false,
  },
  {
    id: 4,
    make: "Santa Cruz",
    model: "Blur",
    suspensionTravel: 100,
    wheelSize: "29",
    ridingStyle: "Cross-Country",
    terrain: "Race Course",
    skillLevel: "Intermediate Advanced",
    price: 5099,
    description:
      "We tapped into everything we’ve learned from years of making the highest quality carbon full-suspension bikes and added the super-efficient Superlight™ suspension to make a World Cup-winning XC race bike. The Blur isn’t guaranteed to make you a race winner but being the lightest, full-suspension carbon XC bike we’ve ever made, it might be the difference between claiming first place...or just crossing the line.",
    imageUrl:
      "https://www.santacruzbicycles.com/_next/image?url=https%3A%2F%2Fimages.prismic.io%2Fsantacruzbikesstatic%2F52baacaf-e92f-4001-ade5-33de28d7c034_MY24_blur_silver.jpg%3Fauto%3Dcompress%2Cformat&w=1400&q=99",
    favorite: false,
  },
  {
    id: 20,
    make: "Santa Cruz",
    model: "V10",
    suspensionTravel: 215,
    wheelSize: "29",
    ridingStyle: "Downhill",
    terrain: "Bike Park",
    skillLevel: "Advanced",
    price: 8500,
    description:
      "The Santa Cruz V10 is a high-performance downhill mountain bike built for speed and stability. It's designed to handle the most challenging terrain with ease, making it the perfect choice for riders who demand the best.",
    imageUrl:
      "https://images.prismic.io/santacruzbikesstatic/1ddbc031-5893-4cb6-b799-88a3929dbc7d_MY24_V10_8_profile_mobile.jpg?auto=compress,format",
    favorite: false,
  },
  {
    id: 5,
    make: "Ibis",
    model: "Exie",
    suspensionTravel: 100,
    wheelSize: "29",
    ridingStyle: "Cross Country",
    terrain: "Race Course",
    skillLevel: "Intermediate Advanced",
    price: 6999,
    description:
      "The Exie USA is a World-Cup winning cross-country race bike that flat out shreds. With a sub 2,000g frame weight and dw-link suspension, it offers a stunning combination of pedaling efficiency and downhill performance. We designed, built, and test­ed it in our Santa Cruz factory, which is pow­ered by the warm Cal­i­for­nia sunshine.",
    imageUrl:
      "https://ibiscycles.imgix.net/images/Bikes/Exie-for-All-Rebrand/Ibis-Exie-For-All-Front-Quarter-White.jpg?fit=clip&q=90&w=800&s=852015c30641c1b6d5b409a82d9dc256",
    favorite: false,
  },
  {
    id: 6,
    make: "Ibis",
    model: "Ripley",
    suspensionTravel: 120,
    wheelSize: "29",
    ridingStyle: "Trail",
    terrain: "Smooth and flowy with some technical rocks",
    skillLevel: "Beginner Intermediate",
    price: 4199,
    description:
      "The Ripley is our snappy, flickable, playful, fast, lightweight, and versatile 29” trail bike Its combination of modern geometry, a stiff lightweight carbon chassis, and 120mm of ultra efficient dw-link travel, means it’s equally happy popping off bonus lines as it is crushing all day epics.",
    imageUrl:
      "https://ibiscycles.imgix.net/images/Bikes/Ripley-V4S/Learn/Ripley-Siren-X01.jpg?fit=clip&q=90&w=800&s=07819c859490ac95a8e4a5f853e597d0",
    favorite: false,
  },
  {
    id: 7,
    make: "Ibis",
    model: "Ripmo",
    suspensionTravel: 147,
    wheelSize: "29",
    ridingStyle: "Trail",
    terrain: "Rocky chunky and technical",
    skillLevel: "Intermediate Advanced",
    price: 4424,
    description:
      "What if we took everybody’s favorite bike and made it a little slacker and little longer? Hell, what if we made it more progressive and coil compatible? And that’s exactly what we did for the Ripmo V2S. Active ingredients include: 29” wheels, berm-defying cornering tendencies, and a love for long rides.",
    imageUrl:
      "https://ibiscycles.imgix.net/images/Bikes/Ripmo-AF-UDH/Complete/RipmoAF-UDH-CinnabonBronze-SLX-FrontQuarter.jpg?fit=clip&q=90&w=800&s=71d5cf4a05830d08f72f6650ae3373c9",
    favorite: false,
  },
  {
    id: 8,
    make: "Ibis",
    model: "HD6",
    suspensionTravel: 165,
    wheelSize: "MX 29/27.5",
    ridingStyle: "Enduro",
    terrain: "Rocky chunky and technical",
    skillLevel: "Intermediate Advanced",
    price: 6099,
    description:
      "The HD6 is the evolution of one of the most successful enduro bikes in history. Designed with input from our Enduro World Cup team and building upon our award-winning Ripmo and HD lines, the HD6 features increased travel, a completely redesigned suspension layout, and mixed wheels.",
    imageUrl:
      "https://ibiscycles.imgix.net/images/Bikes/HD6/Studio/Ibis-HD6-Side-Profile-1.jpg?fit=clip&q=90&w=800&s=a9663bfa203e1206f4aebfc5cbca5d7d",
    favorite: false,
  },
  {
    id: 9,
    make: "Yeti",
    model: "SB120",
    suspensionTravel: 120,
    wheelSize: "29",
    ridingStyle: "Trail",
    terrain: "Smooth and flowy with some technical rocks",
    skillLevel: "Beginner Intermediate",
    price: 4640,
    description:
      "Forget the numbers. Mute the speculation. Let the other guys invent cute alternatives for “cross country.” Steer clear of pigeonholes and limiting beliefs. Strap on your blinders and go get lost. Then decide what the SB120 means to you. And you alone.",
    imageUrl:
      "https://cdn11.bigcommerce.com/s-5zdahzyh66/images/stencil/2880w/attribute_rule_images/598641_source_1708987697.png",
    favorite: false,
  },
  {
    id: 10,
    make: "Yeti",
    model: "SB135",
    suspensionTravel: 135,
    wheelSize: "29",
    ridingStyle: "Trail",
    terrain: "Smooth and flowy with some technical rocks",
    skillLevel: "Beginner Intermediate",
    price: 4800,
    description:
      "Begging for your input, chomping to respond. Flick it, pedal it, pump it to the moon. A stoke-making mutation of fun-focused DNA, blinding proof that less can be a whole lot more. Come out to play. You bet your ass the SB135 is still down.",
    imageUrl:
      "https://cdn11.bigcommerce.com/s-5zdahzyh66/images/stencil/2880w/attribute_rule_images/598046_source_1708988716.png",
    favorite: false,
  },
  {
    id: 11,
    make: "Yeti",
    model: "SB165",
    suspensionTravel: 165,
    wheelSize: "MX 29/27.5",
    ridingStyle: "Enduro",
    terrain: "Rocky chunky and technical",
    skillLevel: "Intermediate Advanced",
    price: 6300,
    description:
      "We said it already knows. And now it knows better. Proven worthy time and again at Rampage, reconfigured to fit the bill as zero-hesitation go-to for whatever your pleasure. Un-rack it for all the park laps, pedal it on character-building epics, push it up spooky steep darksides “nobody” knows about. Whatever the question, unharden your decisions. You ask. It gives.",
    imageUrl:
      "https://cdn11.bigcommerce.com/s-5zdahzyh66/images/stencil/2880w/attribute_rule_images/600115_source_1715792466.png",
    favorite: false,
  },
  {
    id: 12,
    make: "Yeti",
    model: "ASR",
    suspensionTravel: 115,
    wheelSize: "29",
    ridingStyle: "Cross-Country",
    terrain: "Race Course",
    skillLevel: "Intermediate Advanced",
    price: 5600,
    description:
      "A decade ago we peaced out of the lycra game. While we were busy getting down, XC got a lot more X, calling for the comeback of a legend. The ASR helps today’s racers be faster where they have to be. On first blush it may appear to have peers, but don’t get it twisted. The reincarnated ASR is a lot like nothing else.",
    imageUrl:
      "https://cdn11.bigcommerce.com/s-5zdahzyh66/images/stencil/2880w/attribute_rule_images/599997_source_1710780534.png",
    favorite: false,
  },
  {
    id: 13,
    make: "YT Industries",
    model: "Capra",
    suspensionTravel: 170,
    wheelSize: "MX 29/27.5",
    ridingStyle: "Enduro",
    terrain: "Rocky chunky and technical",
    skillLevel: "Intermediate Advanced",
    price: 4000,
    description:
      "The YT Capra is a versatile enduro bike designed for aggressive trail riding and racing. With its excellent suspension and geometry, it offers exceptional performance on rough and technical terrain.",
    imageUrl:
      "https://cdn-prod.yt-industries.com/media/image/2d/0d/fc/CAPRA-MX-CF-Core5-LiquidMetal-Front.png",
    favorite: false,
  },
  {
    id: 14,
    make: "YT Industries",
    model: "Jeffsy",
    suspensionTravel: 150,
    wheelSize: "MX 29/27.5",
    ridingStyle: "Trail",
    terrain: "Rocky chunky and technical",
    skillLevel: "Beginner Intermediate",
    price: 3500,
    description:
      "The YT Jeffsy is a trail bike that balances climbing efficiency with descending capability. It is perfect for riders looking for an all-rounder that can handle a variety of trails with ease.",
    imageUrl:
      "https://cdn-prod.yt-industries.com/media/image/ca/b5/a7/JEFFSY-MK3-CF-Core4-CrimsonRed-Front_wEXXNJ0KkCSyic.png",
    favorite: false,
  },
  {
    id: 15,
    make: "YT Industries",
    model: "Izzo",
    suspensionTravel: 130,
    wheelSize: "29",
    ridingStyle: "Trail",
    terrain: "Smooth and flowy with some technical rocks",
    skillLevel: "Beginner Intermediate",
    price: 3200,
    description:
      "The YT Izzo is a lightweight trail bike built for speed and efficiency. It is ideal for cross-country and light trail riding, offering a nimble and responsive ride.",
    imageUrl:
      "https://cdn-prod.yt-industries.com/media/image/d1/d5/0c/IZZO-29-CF-Core3-CreamYellow-Front_w.png",
    favorite: false,
  },
  {
    id: 16,
    make: "YT Industries",
    model: "Tues",
    suspensionTravel: 200,
    wheelSize: "MX 29/27.5",
    ridingStyle: "Downhill",
    terrain: "Bike Park",
    skillLevel: "Advanced",
    price: 4500,
    description:
      "The YT Tues is a dedicated downhill bike designed to handle the most challenging descents. With its robust construction and top-tier suspension, it excels in downhill racing and extreme freeride conditions.",
    imageUrl:
      "https://cdn-prod.yt-industries.com/media/image/b6/6e/f6/TUES-MK4-MX-CF-Core2-FogGreen-Frontpw7GUBOUAqRXF.png",
    favorite: false,
  },
  {
    id: 17,
    make: "Cannondale",
    model: "Habit Carbon 2",
    suspensionTravel: 130,
    wheelSize: "29",
    ridingStyle: "Trail",
    terrain: "Smooth and flowy with some technical rocks",
    skillLevel: "Beginner Intermediate",
    price: 6200,
    description:
      "The Cannondale Habit Carbon 2 is a versatile trail bike that combines agility and stability. It's designed for all-around trail riding with responsive handling and balanced suspension.",
    imageUrl:
      "https://embed.widencdn.net/img/dorelrl/8ayvhjvghd/1100px@1x/C23_C23201U_Habit_Crb_2_MGO_PD.webp?color=FEFAF0&q=99",
    favorite: false,
  },
  {
    id: 18,
    make: "Cannondale",
    model: "Jekyll 2",
    suspensionTravel: 170,
    wheelSize: "29",
    ridingStyle: "Enduro",
    terrain: "Rocky chunky and technical",
    skillLevel: "Intermediate Advanced",
    price: 5800,
    description:
      "The Cannondale Jekyll 2 is an aggressive enduro bike built for big mountain riding. With its advanced suspension system and progressive geometry, it excels on the most demanding trails.",
    imageUrl:
      "https://embed.widencdn.net/img/dorelrl/biearlko0t/1100px@1x/C21_C21102U_Jekyll_1_GRA_PD.webp?color=eff2f4&q=99",
    favorite: false,
  },
  {
    id: 19,
    make: "Cannondale",
    model: "Scalpel Carbon 3",
    suspensionTravel: 100,
    wheelSize: "29",
    ridingStyle: "Cross-Country",
    terrain: "Race Course",
    skillLevel: "Intermediate Advanced",
    price: 5000,
    description:
      "The Cannondale Scalpel Carbon 3 is a high-performance cross-country bike designed for speed and efficiency. It's perfect for racing and fast-paced trail riding, offering a lightweight and responsive ride.",
    imageUrl:
      "https://embed.widencdn.net/img/dorelrl/fcyykd9fnk/1100px@1x/C21_C24852U_Scalpel_Crb_SE_2_BKM_PD.webp?color=E4E8EC&q=99",
    favorite: false,
  },
    {
    id: 21,
    make: "Rocky Mountain",
    model: "Altitude",
    suspensionTravel: 160,
    wheelSize: "29",
    ridingStyle: "Trail",
    terrain: "Rocky chunky and technical",
    skillLevel: "Intermediate Advanced",
    price: 6999,
    description:
      "The Rocky Mountain Altitude is a versatile all-mountain bike that's equally at home on technical climbs and fast descents. It features modern geometry and efficient suspension, making it ideal for riders who want one bike to do it all.",
    imageUrl:
      "https://bikes.com/cdn/shop/files/Web_MY24__B0331-BLACKBLACK_Altitude_A30_C2_29_Profile_1.jpg?v=1710176521&width=2500",
    favorite: false,
  },
  {
    id: 22,
    make: "Rocky Mountain",
    model: "Element",
    suspensionTravel: 120,
    wheelSize: "29",
    ridingStyle: "Cross-Country",
    terrain: "Race Course",
    skillLevel: "Intermediate Advanced",
    price: 4999,
    description:
      "The Rocky Mountain Element is a high-performance cross-country bike designed for speed and efficiency. It features lightweight construction and a responsive ride, making it perfect for racing and fast-paced trail riding.",
    imageUrl:
      "https://bikes.com/cdn/shop/files/Web_MY22_Element_C70_C1_29_Profile_81b29f5e-0ab4-48c0-9f46-43aaf113f9e2.jpg?v=1713957821&width=2880",
    favorite: false,
  },
  {
    id: 23,
    make: "Rocky Mountain",
    model: "Slayer",
    suspensionTravel: 170,
    wheelSize: "29",
    ridingStyle: "Enduro",
    terrain: "Rocky chunky and technical",
    skillLevel: "Intermediate Advanced",
    price: 7999,
    description:
      "The Rocky Mountain Slayer is a high-performance enduro bike built for aggressive riding. It features long-travel suspension and a slack geometry for confident handling in rough terrain, making it the perfect choice for riders who want to push their limits.",
    imageUrl:
      "https://resources.bikes.com/sites/default/files/styles/model_image_slider/public/models/Web_Slayer_C90_C1_Profile_0.jpg?itok=vQy5K-jY",
    favorite: false,
  },
  {
    id: 24,
    make: "Rocky Mountain",
    model: "Instinct",
    suspensionTravel: 140,
    wheelSize: "29",
    ridingStyle: "Trail",
    terrain: "Smooth and flowy with some technical rocks",
    skillLevel: "Beginner Intermediate",
    price: 5999,
    description:
      "The Rocky Mountain Instinct is a versatile trail bike that's equally at home on technical climbs and fast descents. It features modern geometry and efficient suspension, making it ideal for all-day adventures in the mountains.",
    imageUrl:
      "https://www.sefiles.net/images/library/large/rocky-mountain-instinct-carbon-50-419840-1.png",
    favorite: false,
  },
  {
    id: 25,
    make: "Evil",
    model: "Offering",
    suspensionTravel: 140,
    wheelSize: "29",
    ridingStyle: "Trail",
    terrain: "Smooth and flowy with some technical rocks",
    skillLevel: "Beginner Intermediate",
    price: 6599,
    description:
      "The Evil Offering LS is a versatile trail bike that's equally at home on technical climbs and fast descents. It features long-travel suspension and a slack geometry for confident handling in rough terrain.",
    imageUrl:
      "https://www.evil-bikes.com/cdn/shop/files/EVL-WM-073-offering-v2-wasabi-shadow-gx-super-deluxe-side-evil-white.jpg?v=1706055372",
    favorite: false,
  },
  {
    id: 26,
    make: "Evil",
    model: "Insurgent",
    suspensionTravel: 151,
    wheelSize: "29",
    ridingStyle: "Enduro",
    terrain: "Rocky chunky and technical",
    skillLevel: "Intermediate Advanced",
    price: 7299,
    description:
      "The Evil Insurgent LS is a high-performance enduro bike designed for aggressive riding. It features long-travel suspension and a slack geometry for confident handling in rough terrain, making it the perfect choice for riders who want to push their limits.",
    imageUrl:
      "https://secretspotcyclery.com/cdn/shop/products/EvilInsurgentSide_GX_SpaceBot_MX_1024x1024@2x.jpg?v=1673521123",
    favorite: false,
  },
  {
    id: 27,
    make: "Evil",
    model: "Wreckoning",
    suspensionTravel: 166,
    wheelSize: "29",
    ridingStyle: "Enduro",
    terrain: "Rocky chunky and technical",
    skillLevel: "Intermediate Advanced",
    price: 7699,
    description:
      "The Evil Wreckoning LS is a high-performance enduro bike designed for aggressive riding. It features long-travel suspension and a slack geometry for confident handling in rough terrain, making it the perfect choice for riders who want to push their limits.",
    imageUrl:
      "https://ridebicycles.com/cdn/shop/files/Side_GX_Clay-Porter_535x.jpg?v=1704914863",
    favorite: false,
  },
  {
    id: 28,
    make: "Nukeproof",
    model: "Dissent Carbon 297",
    suspensionTravel: 200,
    wheelSize: "29",
    ridingStyle: "Downhill",
    terrain: "Bike Park",
    skillLevel: "Advanced",
    price: 7499,
    description:
      "The Nukeproof Dissent Carbon 297 is a high-performance downhill mountain bike built for high speed and major fun! Downhill bikes are designed to be the ultimate tool to take on the gnarliest terrain. With 200mm of front and rear travel to enable riders to descend the roughest terrain, the steepest gradients and send the biggest jumps.",
    imageUrl: "https://nukeproof.com/cdn/shop/products/Dissent290COMPCarbonMountainBike_2023-GXDH_NP1-1089958971109copy_1200x1200.jpg?v=1681890312",
    favorite: false,
  },
  {
    id: 29,
    make: "Nukeproof",
    model: "Giga 290",
    suspensionTravel: 180,
    wheelSize: "29",
    ridingStyle: "Enduro",
    terrain: "Rocky chunky and technical",
    skillLevel: "Intermediate Advanced",
    price: 6999,
    description:
      "The Nukeproof Giga 290 Carbon is a high-performance enduro bike designed for aggressive riding. It features long-travel suspension and a slack geometry for confident handling in rough terrain, making it the perfect choice for riders who want to push their limits.",
    imageUrl: "https://cuttingedgect.com/cdn/shop/files/Artboard1_11ab3a45-e0b5-4ed0-b229-f56e2ced9a92.png?v=1697121932",
    favorite: false,
  },
  {
    id: 30,
    make: "Nukeproof",
    model: "Mega 290",
    suspensionTravel: 170,
    wheelSize: "29",
    ridingStyle: "Enduro",
    terrain: "Rocky chunky and technical",
    skillLevel: "Intermediate Advanced",
    price: 6699,
    description:
      "The Nukeproof Mega 290 Carbon is a high-performance enduro bike designed for aggressive riding. It features long-travel suspension and a slack geometry for confident handling in rough terrain, making it the perfect choice for riders who want to push their limits.",
    imageUrl: "https://p.vitalmtb.com/photos/products/31658/photos/67243/original_2021_Nukeproof_Mega_RS.jpg?VersionId=0URgvoUOH.CS01pjzhqIEjNol6zBBYrt",
    favorite: false,
  },
  {
    id: 31,
    make: "Nukeproof",
    model: "Reactor 290",
    suspensionTravel: 130,
    wheelSize: "29",
    ridingStyle: "Trail",
    terrain: "Smooth and flowy with some technical rocks",
    skillLevel: "Beginner Intermediate",
    price: 6499,
    description:
      "The Nukeproof Reactor 290 Carbon is a versatile trail bike that's equally at home on technical climbs and fast descents. It features modern geometry and efficient suspension, making it ideal for all-day adventures in the mountains.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTD65-4XAOMgy6zpyZvtf-n32s_VyXQ0QHLyRrP9GpjGA&s",
    favorite: false,
  },
  {
    id: 32,
    make: "Transition",
    model: "TR11",
    suspensionTravel: 200,
    wheelSize: "29",
    ridingStyle: "Downhill",
    terrain: "Bike Park",
    skillLevel: "Advanced",
    price: 8999,
    description:
      "The Transition TR11 is a high-performance downhill mountain bike built for speed and stability. It's designed to handle the most challenging terrain with ease, making it the perfect choice for riders who demand the best.",
    imageUrl: "https://transitionbikes.com/images/TR11_2022_Gallery_1.jpg",
    favorite: false,
  },
  {
    id: 33,
    make: "Transition",
    model: "Patrol",
    suspensionTravel: 170,
    wheelSize: "29",
    ridingStyle: "Enduro",
    terrain: "Rocky chunky and technical",
    skillLevel: "Intermediate Advanced",
    price: 6899,
    description:
      "The Transition Patrol is a high-performance enduro bike built for aggressive riding. It features long-travel suspension and a slack geometry for confident handling in rough terrain, making it the perfect choice for riders who want to push their limits.",
    imageUrl: "https://transitionbikes.com/images/2023_PatrolCarbon_Gallery2B.jpg",
    favorite: false,
  },
  {
    id: 34,
    make: "Scott",
    model: "Spark RC",
    suspensionTravel: 120,
    wheelSize: "29",
    ridingStyle: "Cross-Country",
    terrain: "Race Course",
    skillLevel: "Intermediate Advanced",
    price: 7999,
    description:
      "The Scott Spark RC Team Issue TR is a high-performance cross-country bike designed for speed and efficiency. It features lightweight construction and responsive handling, making it the perfect choice for racing and fast-paced trail riding.",
    imageUrl:
      "https://asset.scott-sports.com/fit-in/2000x2000/420/420643_2030849_3.png?signature=a9c7640223c20ce80c78db9db2ec4bda60b57f52a5b43d10aee1e4b294e1c39a",
    favorite: false,
  },
  {
    id: 35,
    make: "Scott",
    model: "Genius",
    suspensionTravel: 150,
    wheelSize: "29",
    ridingStyle: "Trail",
    terrain: "Rocky chunky and technical",
    skillLevel: "Beginner Intermediate",
    price: 6499,
    description:
      "The Scott MTB Trail Genius is a versatile trail bike that's equally at home on technical climbs and fast descents. It features modern geometry and efficient suspension, making it ideal for all-day adventures in the mountains.",
    imageUrl:
      "https://asset.scott-sports.com/fit-in/2000x2000/290/290140_1920344_4.png?signature=8bfa27c77d7768aacf9ee3fec5738e3cd8c188cb636f6803c5f1c4b63facb1c9",
    favorite: false,
  },
];

module.exports = bikeData;

